vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        plats:
            uri_prefix: /images/plats
            upload_destination: '%kernel.project_dir%/public/images/plats'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

